### ISSUE TITLE
Maybe I know why WiFi works slowly because of Bluetooth. When I don't inject Bluetooth driver, my WiFi speed is normal.

### ISSUE THREAD

**Issue by Johanan2** [flyingcherryblossoms/Hackintosh-fl8000un-x542un#1]

**Comment by flyingcherryblossoms** [comment]
Thanks for your feedback, I have changed my wifi card to AX210 already and Win11 is nice for me. 
This repo is out of date and I'm not going to update it recently .
    If you want more info about the EFI, you can see https://github.com/alexanderkin/ASUS-FL8000UQ-Hackintosh for help, I just move it and add some drivers from this repo. And the wifi and bluetooth driver came from https://www.longzc.cn/archives/330. The author didn't update it for a long time. 
    And I have searched in the internet there are some ways to solve this problem, but I didn't try it. https://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1797351

**Comment by Johanan2** [comment]
Thanks,I will try
