### ISSUE TITLE
如何使用带驱动EFI

### ISSUE THREAD

**Issue by OutlierStar** [flyingcherryblossoms/Hackintosh-fl8000un-x542un#2]
现在已经使用安装EFI通过OC引导安装好了Mac OS Catalina，但是声卡，有线无线网卡，蓝牙等都不正常，怎么使用那个带驱动的efi，直接使用进不去oc

**Comment by OutlierStar** [comment]
Catalina下安装使用efi可以用，带驱动efi进不了oc

**Comment by flyingcherryblossoms** [comment]
这个仓库已经过期了，可以参考https://github.com/KKKIIINNN/ASUS-FL8000UQ-Hackintosh
